
services:
  glue_pyspark:
    image: public.ecr.aws/glue/aws-glue-libs:5
    command: ["pyspark"]
    volumes:
      - "${WORKSPACE_LOCATION}:/home/glue_user/workspace/" # Mount your project workspace
    environment:
      - DISABLE_SSL=true
    ports:
      - "4040:4040"    # Spark UI
      - "18080:18080"  # Spark History Server 
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
 