
services:
  glue_pyspark:
    image: public.ecr.aws/glue/aws-glue-libs:5
    command: ["pyspark"]
    volumes:
      - "./:/home/glue_user/workspace/" # Mount your project workspace
    environment:
      - DISABLE_SSL=true
    ports:
      - "4042:4040"    # Spark UI
      - "18082:18080"  # Spark History Server 
    tty: true
    stdin_open: true
    deploy:
      restart_policy:
        condition: on-failure
 