name: Glue Job CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [main]

jobs:
  test-glue-job:
    name: Test Glue Job
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and start Glue container
        run: docker compose up -d --build

      - name: Run Glue job using spark-submit
        run: |
          CONTAINER_ID=$(docker ps -qf "name=glue_pyspark")
          docker exec "$CONTAINER_ID" bash -c "cd /home/glue_user/workspace/glue_jobs && spark-submit glue_main.py"

  deploy-glue-job:
    name: Deploy Glue Job (main)
    if: github.ref == 'refs/heads/main'
    needs: test-glue-job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Glue script to S3
        run: aws s3 cp glue_jobs/glue_main.py ${{ secrets.S3_SCRIPT_PATH }}

      - name: Create or Update AWS Glue Job
        run: |
          JOB_NAME="${{ secrets.GLUE_JOB_NAME }}"
          SCRIPT_PATH="${{ secrets.S3_SCRIPT_PATH }}"
          ROLE_ARN="${{ secrets.GLUE_ROLE_ARN }}"

          echo "Checking if Glue job '$JOB_NAME' exists..."

          if aws glue get-job --job-name "$JOB_NAME" >/dev/null 2>&1; then
            echo "Updating Glue job..."

            cat <<EOF > job-update.json
{
  "Command": {
    "Name": "glueetl",
    "ScriptLocation": "$SCRIPT_PATH",
    "PythonVersion": "3"
  }
}
EOF

            aws glue update-job \
              --job-name "$JOB_NAME" \
              --job-update file://job-update.json
          else
            echo "Creating Glue job..."

            cat <<EOF > job-create.json
{
  "Name": "$JOB_NAME",
  "Role": "$ROLE_ARN",
  "Command": {
    "Name": "glueetl",
    "ScriptLocation": "$SCRIPT_PATH",
    "PythonVersion": "3"
  },
  "GlueVersion": "4.0",
  "MaxCapacity": 2,
  "Timeout": 10
}
EOF

            aws glue create-job --cli-input-json file://job-create.json
          fi
